// Copyright (C) 2025-2026 Alain Bouchard
// SPDX-License-Identifier: Apache-2.0

//! Does this reach the same verdict as `nmos/oauth2` on the same tokens?
//!
//! `oauth2_cases.json` is generated by `nmos/api/tests/_oauth2_corpus.py`: real
//! tokens signed with real keys, each carrying the verdict *that* implementation
//! returned. This asserts the same three answers here -- whether the signature
//! verified, whether access was allowed, and whether the token counted as valid.
//!
//! The third is the one worth having. `verified` and `allowed` would be caught
//! by almost any test; `valid_token` is the 401-or-403 distinction, and it is
//! the sort of thing two implementations drift on silently because both look
//! like "denied".
//!
//! Regenerate with `python -m nmos.api.tests._oauth2_corpus` whenever the
//! Python changes; `test_oauth2_corpus.py` fails if the recording goes stale.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic
)]

use std::path::Path;

use nmos_registry_http::oauth2::{Jwks, validate_access, validate_token_with_claims};
use serde_json::Value;

#[test]
fn every_case_reaches_the_same_verdict_as_the_python() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/oauth2_cases.json");
    let corpus: Value = serde_json::from_slice(
        &std::fs::read(&path)
            .unwrap_or_else(|_| panic!("{} is missing -- regenerate it", path.display())),
    )
    .expect("the corpus parses");

    let jwks = Jwks::from_value(&corpus["jwks"]);
    assert_eq!(jwks.keys.len(), 2, "the keyset did not parse");

    let now = corpus["now"].as_f64().expect("now");
    let serial = corpus["serial_number"].as_str().expect("serial");
    let cert_names: Vec<String> = corpus["tls_server_cert_names"]
        .as_array()
        .expect("cert names")
        .iter()
        .map(|name| name.as_str().expect("a string").to_owned())
        .collect();

    let cases = corpus["cases"].as_array().expect("cases");
    assert!(!cases.is_empty(), "an empty corpus proves nothing");

    let mut differing = Vec::new();
    for case in cases {
        let name = case["name"].as_str().expect("name");
        let token = case["token"].as_str().expect("token");
        let read_write = case["read_write"].as_bool().expect("read_write");

        let (verified, claims) = validate_token_with_claims(token, &jwks);
        let (allowed, valid_token) = if verified {
            validate_access(
                &claims,
                read_write,
                "query",
                serial,
                &cert_names,
                false,
                false,
                now,
            )
        } else {
            (false, false)
        };

        let ours = (verified, allowed, valid_token);
        let theirs = (
            case["verified"].as_bool().expect("verified"),
            case["allowed"].as_bool().expect("allowed"),
            case["valid_token"].as_bool().expect("valid_token"),
        );
        if ours != theirs {
            differing.push(format!(
                "  {name}: python (verified, allowed, valid_token) = {theirs:?}, \
                 here = {ours:?}",
            ));
        }
    }

    assert!(
        differing.is_empty(),
        "{} of {} cases differ from the Python:\n{}",
        differing.len(),
        cases.len(),
        differing.join("\n"),
    );
}

#[test]
fn the_corpus_actually_exercises_both_outcomes() {
    // A corpus where everything fails would pass the parity test while proving
    // nothing about the accepting path, and vice versa. This is the guard
    // against a generator change quietly hollowing the check out.
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/oauth2_cases.json");
    let corpus: Value =
        serde_json::from_slice(&std::fs::read(&path).expect("read")).expect("the corpus parses");
    let cases = corpus["cases"].as_array().expect("cases");

    let verified = cases.iter().filter(|c| c["verified"] == true).count();
    let allowed = cases.iter().filter(|c| c["allowed"] == true).count();
    let invalid = cases
        .iter()
        .filter(|c| c["verified"] == true && c["valid_token"] == false)
        .count();
    let forbidden = cases
        .iter()
        .filter(|c| c["valid_token"] == true && c["allowed"] == false)
        .count();

    assert!(verified >= 5, "too few tokens verify: {verified}");
    assert!(
        cases.len() - verified >= 5,
        "too few tokens fail to verify: {}",
        cases.len() - verified,
    );
    assert!(allowed >= 3, "no accepting path exercised: {allowed}");
    // The two halves of the distinction this file exists for.
    assert!(invalid >= 1, "no 401-after-verification case: {invalid}");
    assert!(forbidden >= 1, "no 403 case: {forbidden}");
}
