// Copyright (C) 2025-2026 Alain Bouchard
// SPDX-License-Identifier: Apache-2.0

//! Differential test: `format_repr` must print floats exactly as Python does.
//!
//! `float_cases.json` records what CPython's `repr` actually produced,
//! generated by `nmos/codegen/tests/_float_corpus.py`. Values travel as their
//! IEEE-754 bit pattern so the Rust side reconstructs the same float rather
//! than one that merely prints the same -- a decimal literal in JSON would not
//! survive the round trip for denormals or for values near the precision limit.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use nmos_json::engine::format_repr;

#[derive(Debug, serde::Deserialize)]
struct Case {
    bits: String,
    formatted: String,
}

#[test]
fn format_repr_matches_python_for_every_case() {
    let cases: Vec<Case> = serde_json::from_str(include_str!("float_cases.json"))
        .expect("the float corpus is valid JSON");
    assert!(cases.len() > 400, "corpus looks truncated: {}", cases.len());

    let mut wrong = Vec::new();
    let mut ties = 0usize;
    for case in &cases {
        let bits: u64 = case.bits.parse().expect("bit pattern is a u64");
        let value = f64::from_bits(bits);
        let got = format_repr(value);
        if got == case.formatted {
            continue;
        }

        // A difference is allowed ONLY when it is a tie: the double sits
        // exactly halfway between two equally short decimals, and Python rounds
        // half to even while Rust rounds half away from zero. Both spellings
        // read back as the same double, so no consumer can tell them apart.
        //
        // This is a property, not an allowlist. It permits that one class and
        // nothing else -- a genuinely wrong digit, a lost exponent or a
        // truncated value all still fail, because they would either fail to
        // round-trip or differ in length.
        let both_round_trip =
            got.parse::<f64>() == Ok(value) && case.formatted.parse::<f64>() == Ok(value);
        let equally_short = got.len() == case.formatted.len();

        if both_round_trip && equally_short {
            ties += 1;
        } else {
            wrong.push(format!(
                "bits {bits}: rust {got:?} != python {:?} \
                 (round_trip={both_round_trip}, same_len={equally_short})",
                case.formatted,
            ));
        }
    }

    // Guard the guard: if ties ever stopped happening, the tolerance above
    // would be silently covering nothing, and a later regression could hide
    // behind it. The corpus deliberately contains random bit patterns so this
    // stays non-zero.
    assert!(
        ties > 0,
        "no ties in the corpus -- the tie tolerance is no longer exercised",
    );
    assert!(
        ties < cases.len() / 50,
        "{ties} ties of {} is too many to be tie-breaking; something else is \
         differing",
        cases.len(),
    );

    assert!(
        wrong.is_empty(),
        "{} of {} floats format differently:\n  {}",
        wrong.len(),
        cases.len(),
        wrong
            .iter()
            .take(20)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n  "),
    );
}
